//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvertorsIT.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentStatusHistory
    {
        public int HistoryID { get; set; }
        public int EquipmentID { get; set; }
        public int OldStatusID { get; set; }
        public int NewStatusID { get; set; }
        public int ChangedByUserID { get; set; }
        public Nullable<System.DateTime> ChangedAt { get; set; }
        public string Comment { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual EquipmentStatuses EquipmentStatuses { get; set; }
        public virtual EquipmentStatuses EquipmentStatuses1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
