//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvertorsIT.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.EquipmentStatusHistory = new HashSet<EquipmentStatusHistory>();
            this.RepairRequests = new HashSet<RepairRequests>();
        }
    
        public int EquipmentID { get; set; }
        public string SerialNumber { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> ResponsibleUserID { get; set; }
        public int TypeID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual ICollection<EquipmentStatusHistory> EquipmentStatusHistory { get; set; }
        public virtual Users Users { get; set; }
        public virtual EquipmentStatuses EquipmentStatuses { get; set; }
        public virtual EquipmentTypes EquipmentTypes { get; set; }
        public virtual ICollection<RepairRequests> RepairRequests { get; set; }
    }
}
