//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvertorsIT.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentTypes
    {
        public EquipmentTypes()
        {
            this.Equipment = new HashSet<Equipment>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public string Category { get; set; }
        public Nullable<int> WarrantyMonths { get; set; }
    
        public virtual ICollection<Equipment> Equipment { get; set; }
    }
}
