//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvertorsIT.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentStatuses
    {
        public EquipmentStatuses()
        {
            this.Equipment = new HashSet<Equipment>();
            this.EquipmentStatusHistory = new HashSet<EquipmentStatusHistory>();
            this.EquipmentStatusHistory1 = new HashSet<EquipmentStatusHistory>();
        }
    
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public Nullable<bool> IsAvailableForUse { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual ICollection<EquipmentStatusHistory> EquipmentStatusHistory { get; set; }
        public virtual ICollection<EquipmentStatusHistory> EquipmentStatusHistory1 { get; set; }
    }
}
