//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvertorsIT.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStatuses
    {
        public RequestStatuses()
        {
            this.RepairRequests = new HashSet<RepairRequests>();
        }
    
        public int RequestStatusID { get; set; }
        public string StatusName { get; set; }
        public Nullable<bool> IsFinal { get; set; }
    
        public virtual ICollection<RepairRequests> RepairRequests { get; set; }
    }
}
