//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvertorsIT.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Equipment = new HashSet<Equipment>();
            this.EquipmentStatusHistory = new HashSet<EquipmentStatusHistory>();
            this.RepairRequests = new HashSet<RepairRequests>();
            this.RepairRequests1 = new HashSet<RepairRequests>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public int RoleID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual ICollection<EquipmentStatusHistory> EquipmentStatusHistory { get; set; }
        public virtual ICollection<RepairRequests> RepairRequests { get; set; }
        public virtual ICollection<RepairRequests> RepairRequests1 { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
